kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ include "generic-micro-service.fullname" . }}-configmap
  labels:
    {{- include "generic-micro-service.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
