{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "generic-micro-service.fullname" . }}
  labels:
    {{- include "generic-micro-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "generic-micro-service.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  {{- $cpu := .Values.autoscaling.targetCPUUtilizationPercentage }}
  {{- $mem := .Values.autoscaling.targetMemoryUtilizationPercentage }}
  {{- if or $cpu $mem }}
  metrics:
    {{- if $cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpu }}
    {{- end }}
    {{- if $mem }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mem }}
    {{- end }}
  {{- end }}
{{- end }}
