name: Helm Chart Package and Publish

on:
  workflow_dispatch:
    inputs:
      HELM_CHART_NAME:
        description: 'HELM_CHART_NAME'
        required: true
        type: choice
        options:
          - generic-micro-service
          - generic-micro-service1
          - generic-micro-service2
        default: generic-micro-service
      HELM_CHART_VERSION:
        description: ' HELM_CHART_VERSION'
        required: true
        type: string
        default: 1.1.9
    

env:
  JFROG_REPO_NAME: my-helm-charts
  HELM_CHART_NAME: ${{ inputs.HELM_CHART_NAME }}
  HELM_CHART_VERSION: ${{ inputs.HELM_CHART_VERSION }}
  JFROG_REPO_URL: https://mgirlsos.github.io/my-helm-charts

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.4

      - name: Add Helm repo (JFrog)
        run: |

          helm repo add $JFROG_REPO_NAME $JFROG_REPO_URL
          helm repo update
            #   helm repo add $JFROG_REPO_NAME $JFROG_REPO_URL \
            #     --username ${{ secrets.JFROG_USERNAME }} \
            #     --password ${{ secrets.JFROG_TOKEN }}
   

      - name: Package Helm chart (with dependencies)
        run: |
          helm dependency update ./my-helm-charts/${{ inputs.HELM_CHART_NAME }}
          helm package ./my-helm-charts/${{ inputs.HELM_CHART_NAME }} \
            --version ${{ inputs.HELM_CHART_VERSION }} \
            --destination ./my-helm-charts/
          helm repo index ./my-helm-charts/ --url ${JFROG_REPO_URL}

    #   - name: Upload Helm Chart to JFrog
    #     run: |
    #       curl -H "Authorization: Bearer ${{ secrets.JFROG_TOKEN }}" \
    #         -T ./charts/${HELM_CHART_NAME}-${HELM_CHART_VERSION}.tgz \
    #         "${JFROG_REPO_URL}"
      
      
      - name: Prepare GitHub Pages content (exclude certain directory)
        run: |
          cp -f ./my-helm-charts/index public/my-helm-charts/
          cp -f ./my-helm-charts/${{ inputs.HELM_CHART_NAME }}-${{ inputs.HELM_CHART_VERSION }}.tgz public/my-helm-charts/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          keep_files: true
      - name: Show Helm Chart Info
        run: |
          helm show chart $JFROG_REPO_NAME/$HELM_CHART_NAME --version $HELM_CHART_VERSION
